[package]

name = "partners"
version = "0.1.0"
authors = ["Jonas Nicklas <jonas.nicklas@gmail.com>"]

description = "Switch between multiple git authors"
homepage = "https://github.com/elabs/partners"
readme = "README.md"
license = "MIT"

[dependencies]
docopt = "0.6.74"
