[package]

name = "partners"
version = "0.0.1"
authors = ["Jonas Nicklas <jonas.nicklas@gmail.com>"]

[dependencies]
docopt = "*"

[dependencies.standard_error]
git = "https://github.com/jnicklas/standard_error.git"
